//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `SudokuSolver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package intfc;

public final class solverI implements solver
{
    private final String _name;

    public solverI(String name)
    {
        _name = name;
    }

    @Override
    public void sudokuSolver(com.zeroc.Ice.Current current, int[][] board, int N)
    {
        System.out.println(_name + " says Hello World!");
    }

    @Override
    public boolean callback(com.zeroc.Ice.Current current)
    {
        boolean r = false;
        return r;
    }

    @Override
    public void shutdown(com.zeroc.Ice.Current current)
    {

        System.out.println(_name + " shutting down...");
        current.adapter.getCommunicator().shutdown();
    }
}
